@name=Add Vaccination Center

POST http://localhost:8080/api/centers/add
Authorization: Basic YWRtaW4yOmFkbWluMg==
Content-Type: application/json

{
"address": "63 rue des potiers",
"city": "Nancy",
"name": "Dupond"
}
