version: '3'
services:
  jdk: 
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
  db:
    image: postgres:alpine3.18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kanehuri//974
      POSTGRES_DB: covid-db
    ports:
      - "5432:5432"

networks:
  default:
    driver: bridge