version: '3'
services:
  jdk: 
    build:
      context: .
      dockerfile: dockerfile
  db:
    image: postgres:alpine3.18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kanehuri//974
      POSTGRES_DB: covid-db