version: '3'
services:
  jdk: 
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      - db
    links:
      - db
    ports:
      - "8080:8080"
  db:
    hostname: db
    image: postgres:alpine3.18
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: covid-db
    ports:
      - "5432:5432"
    volumes:
    - ./pgdata:/var/lib/postgresql/data
networks:
  default:
    driver: bridge