@name=Add Vaccination Center

POST http://localhost:8080/api/superadmin/create
Authorization: Basic dXNlcjpwYXNzd29yZA==
Content-Type: application/json

{
"login": "admin",
"password": "admin",
"centerId": "1"
}
