@name=Add Vaccination Center

POST http://localhost:8080/api/superadmin/create
Authorization: Basic YWRtaW4zOmFkbWluMw==
Content-Type: application/json

{
"login": "admin4",
"password": "admin4",
"centerId": "1"
}
