@name=Add Vaccination Center

POST http://localhost:8080/api/superadmin/create
Authorization: Basic YWRtaW4yOmFkbWluMg==
Content-Type: application/json

{
"login": "admin2",
"password": "admin2",
"centerId": "2"
}
