@name=Add Vaccination Center

POST http://localhost:8080/api/superadmin/supercreate
Authorization: Basic dXNlcjpwYXNzd29yZA==
Content-Type: application/json

{
"login": "superadmin",
"password": "superadmin",
"centerId": "1"
}
