@name=Add Vaccination Center

POST http://localhost:8080/api/admin/create
Authorization: Basic YWRtaW46YWRtaW4=
Content-Type: application/json

{
"login": "medecin0",
"password": "medecin2",
"centerId": "2"
}
